defaults:
  - /slam: default

instance: vipe.pipeline.default.DefaultAnnotationPipeline

# Init configs
init:
  camera_type: "pinhole"
  intrinsics: "geocalib"
  instance:
    kf_gap_sec: 2.0
    phrases: 
      - person
      - animal
      - vehicle
      - ball
      - balloon
      - gun
      - pet
      - car
      - bus
    add_sky: true

slam:
  keyframe_depth: unidepth-l
  optimize_intrinsics: ${neq:${..init.intrinsics},"gt"}

# Post-processing configs
post:
  depth_align_model: "adaptive_unidepth-l_svda"

# Output configs
output:
  # Path to save results
  path: vipe_results/
  skip_exists: false

  # Save artifacts and a info file
  save_artifacts: false
  pcd_fusion_mode: backproject
  backproject_pcd_max_points: 8000000
  backproject_pcd_conf_threshold_coef: 0.75
  backproject_pcd_sample_ratio: 0.015
  pcd_tsdf_voxel_length: 0.02
  pcd_tsdf_sdf_trunc: 0.15
  pcd_tsdf_depth_trunc: 5.0

  # Save reconstruction from SLAM
  save_slam_map: false

  # Visualization videos to BASE_PATH/vipe/xxx.mp4
  save_viz: false
  viz_downsample: 2
  viz_attributes: [['rgb', 'instance'], ['depth', 'pcd']]
