[build-system]
requires = ["setuptools>=40.8.0", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint.isort]
lines-between-types = 1
lines-after-imports = 2

[project]
name = "vipe"
description = "NVIDIA Video Pose Engine"
authors = [
    {name = "The ViPE Authors", email = "jiahuih@nvidia.com"},
]
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "numpy",
    "einops",
    "tqdm",
    "imageio[ffmpeg]",
    "opencv-python",
    "gdown",
    "scipy",
    "open3d>=0.19.0",
]

[project.optional-dependencies]
instance = [
    "hydra-core>=1.3.2",
    "iopath>=0.1.10",
    "pillow>=9.4.0",
    "plyfile>=1.1",
    "pycocotools>=2.0.8",
    "segment-anything @ git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588",
    "SAM-2 @ git+https://github.com/sadanand1120/sam2.git@b5df60f857f2ee5f441aefd3594102caed049182",
    "transformers==4.41.0",
    "tokenizers==0.19.1",
    "huggingface-hub==0.23.4",
    "sentencepiece>=0.2.0",
    "ftfy>=6.3.1",
    "regex>=2024.11.6",
]
